#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require "thor"
require "cp8_cli"

module Cp8Cli
  class App < Thor
    desc "start [URL|TITLE]", "Picks up existing issue/creates new ad hoc story and checks out branch"
    def start(name = nil)
      main.start(name)
    end

    desc "submit", "Pushes branch to GitHub and opens a PR"
    method_option :wip, desc: "Flag PR as WIP", type: :boolean
    def submit
      main.submit(options.to_h.symbolize_keys)
    end

    desc "open", "Open current associated issue in browser"
    def open
      main.open
    end

    desc "ci", "Open CI page for current branch"
    def ci
      main.ci
    end

    desc "suggest", "Creates a suggestion branch from new commits, pushes it, opens URL and resets `master` back to `origin/master`."
    def suggest
      main.suggest
    end

    private

      def main
        Main.new
      end
  end
end

Cp8Cli::App.start
