#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require "trello_flow"
require "trollop"


options = Trollop::options do
	banner <<-EOS
Pushes branch to GitHub and opens a PR

Usage:
    git finish
EOS
  opt :wip, "Open [WIP] PR"
  opt :rebase, "Rebase to master"
end

TrelloFlow::Main.new.finish(options)
