#!/usr/bin/env ruby

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '..', 'lib')

require "cp8_cli"
require "trollop"


options = Trollop::options do
	banner <<-EOS
Pushes branch to GitHub and opens a PR

Usage:
    git finish
EOS
  opt :wip, "Open [WIP] PR"
end

Cp8Cli::Main.new.finish(options)
